[[main]]
name = "About"
pageRef = "/about"
weight = 1

[[main]]
name = "Events"
pageRef = "/events"
weight = 2

[[main]]
name = "Resources"
pageRef = "/resources"
weight = 3

[[main]]
name = "Snacks"
pageRef = "/snacks"
weight = 4

[[main]]
name = "Committees"
pageRef = "/committees"
weight = 5
