############# English navigation ##############

# # main menu
# [[main]]
# name = "Home"
# pageRef = "/"
# weight = 1
#
[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
name = "Events"
pageRef = "/events"
weight = 3

[[main]]
name = "Resources"
pageRef = "/resources"
weight = 4

[[main]]
weight = 10
name = "Committees"

[[main]]
parent = "Committees"
name = "Outreach"
pageRef = "/outreach"

[[main]]
parent = "Committees"
name = "Snacks"
pageRef = "/snacks"

[[main]]
parent = "Committees"
name = "E&I"
pageRef = "/ei"

[[main]]
parent = "Committees"
name = "Socials"
pageRef = "/socials"

[[main]]
parent = "Committees"
name = "Projects"
pageRef = "/projects"

# [[main]]
# weight = 4
# name = "Pages"
#
# [[main]]
# parent = "Pages"
# name = "Blog"
# pageRef = "/blog"
#
# [[main]]
# parent = "Pages"
# name = "Contact"
# pageRef = "/contact"
#
# [[main]]
# parent = "Pages"
# name = "Authors"
# pageRef = "/authors"
#
# [[main]]
# parent = "Pages"
# name = "Categories"
# pageRef = "/categories"
#
# [[main]]
# parent = "Pages"
# name = "404 Page"
# pageRef = "/404"
#
#
# # footer menu
# [[footer]]
# name = "About"
# pageRef = "/about"
# weight = 1
#
# [[footer]]
# name = "Elements"
# pageRef = "/elements"
# weight = 2
#
# [[footer]]
# name = "Privacy Policy"
# pageRef = "/privacy-policy"
# weight = 3
