[[main]]
name = "About"
url = "/about"
weight = 1

[[main]]
name = "Events"
url = "/events"
weight = 2

[[main]]
name = "Resources"
url = "/resources"
weight = 3

[[main]]
name = "Snacks"
url = "/snacks"
weight = 4

[[main]]
name = "Committees"
url = "/committees"
weight = 5

[[main]]
name = "Competitions"
parent = "Committees"
url = "/committees/competitions"

[[main]]
name = "Outreach"
parent = "Committees"
url = "/committees/outreach"

[[main]]
name = "Projects"
parent = "Committees"
url = "/committees/projects"

[[main]]
name = "Socials"
parent = "Committees"
url = "/committees/socials"
